spring.application.name=hitbox-admin-api

server.port=8080
server.address=0.0.0.0
server.servlet.context-path=/api/hitbox

# JPA Spring configurations
spring.jpa.hibernate.ddl-auto=update
spring.batch.jdbc.initialize-schema=always
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=hitbox}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:senha01}
spring.datasource.driver-class-name=org.postgresql.Driver

app.upload.dir=${DIR_UPLOADS:uploads}
